Cinema spring 04
Rudiachenko/hibernate-cinema pull request #13
Opened 2020-10-29 19:20 UTC by Rudiachenko

2020-10-30 08:53 UTC, andromash reviewed
Good job!

2020-10-30 08:53 UTC, andromash commented on src/main/java/com/dev/cinema/Main.java
> +    public static void main(String[] args) {
I think you can delete this class already

2020-10-30 08:53 UTC, andromash commented on src/main/java/com/dev/cinema/model/dto/MovieSessionRequestDto.java
>      private Long movieId;
show Time is not null but is it even possible to have a movie session with null cinema hall and movie?

2020-10-30 12:40 UTC, KseniiaMakarova requested changes

2020-10-30 12:40 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +        }
I think this is redundant

2020-10-30 12:40 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +        }
same

2020-10-30 12:40 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/UserController.java
> +    public UserResponseDto get(Authentication authentication) {
let's not change this - this method should return info about any user by his email

2020-10-30 12:40 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/validation/EmailValueValidator.java
> +        return email.matches(EMAIL_REGEX);
let's add null check - and we can remove @NotNull constraint above email field
the problem is that we can not ensure the order of validation

2020-10-31 12:14 UTC, KseniiaMakarova approved these changes

2020-10-31 12:23 UTC, merged