Cinema spring 02
Rudiachenko/hibernate-cinema pull request #8
Opened 2020-10-22 22:06 UTC by Rudiachenko

2020-10-22 22:36 UTC, DariiaPikul requested changes
Merge the previous PR, please, so the old changes won't appear in here

2020-10-22 22:36 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controllers/MovieController.java
> +    @PostMapping("/create")
Let's not use CRUD naming in the URL

2020-10-22 22:36 UTC, DariiaPikul commented on src/main/java/com/dev/cinema/controllers/MovieSessionMapper.java
> +        movieSession.setShowTime(LocalDateTime.parse(movieSessionRequestDto.getShowTime(),
```suggestion
        Movie movie = movieService.get(movieSessionRequestDto.getMovieId());
        movieSession.setShowTime(LocalDateTime.parse(movieSessionRequestDto.getShowTime(),
```

2020-10-23 07:37 UTC, RomanDubovskyi reviewed
you have here files not related to this PR (previous HW) let's remove them
\+ change PR name it's uninformative

2020-10-23 09:19 UTC, closed without merging